Fixes #609 Uncaught Error: Cannot find module 'autonumeric' on v4.4.1
Reverts the changes from `4.4.1` : "Modify the `package.json` configuration `main` field to `browser`"

Signed-off-by: Alexandre Bonneau <alexandre.bonneau@linuxfr.eu>